/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intervigil_micdroid_jni_JNIMicDroid */

#ifndef _Included_com_intervigil_micdroid_jni_JNIMicDroid
#define _Included_com_intervigil_micdroid_jni_JNIMicDroid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intervigil_micdroid_jni_JNIMicDroid
 * Method:    getLiveCorrectionEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intervigil_micdroid_jni_JNIMicDroid_getLiveCorrectionEnabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
