/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intervigil_micdroid_recorder_JNIRecorder */

#ifndef _Included_com_intervigil_micdroid_recorder_JNIRecorder
#define _Included_com_intervigil_micdroid_recorder_JNIRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intervigil_micdroid_recorder_JNIRecorder
 * Method:    jniRecorderStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intervigil_micdroid_recorder_JNIRecorder_jniRecorderStart
  (JNIEnv *, jobject);

/*
 * Class:     com_intervigil_micdroid_recorder_JNIRecorder
 * Method:    jniRecorderStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intervigil_micdroid_recorder_JNIRecorder_jniRecorderStop
  (JNIEnv *, jobject);

/*
 * Class:     com_intervigil_micdroid_recorder_JNIRecorder
 * Method:    jniRecorderCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intervigil_micdroid_recorder_JNIRecorder_jniRecorderCleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_intervigil_micdroid_recorder_JNIRecorder
 * Method:    jniRecorderInitCallback
 * Signature: (ILandroid/media/AudioRecord;Landroid/media/AudioTrack;)V
 */
JNIEXPORT void JNICALL Java_com_intervigil_micdroid_recorder_JNIRecorder_jniRecorderInitCallback
  (JNIEnv *, jobject, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
