/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intervigil_micdroid_recorder_JniRecorder */

#ifndef _Included_com_intervigil_micdroid_recorder_JniRecorder
#define _Included_com_intervigil_micdroid_recorder_JniRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intervigil_micdroid_recorder_JniRecorder
 * Method:    jniRecorderStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intervigil_micdroid_recorder_JniRecorder_jniRecorderStart
  (JNIEnv *, jobject);

/*
 * Class:     com_intervigil_micdroid_recorder_JniRecorder
 * Method:    jniRecorderStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intervigil_micdroid_recorder_JniRecorder_jniRecorderStop
  (JNIEnv *, jobject);

/*
 * Class:     com_intervigil_micdroid_recorder_JniRecorder
 * Method:    jniRecorderCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intervigil_micdroid_recorder_JniRecorder_jniRecorderCleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_intervigil_micdroid_recorder_JniRecorder
 * Method:    jniRecorderInitCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intervigil_micdroid_recorder_JniRecorder_jniRecorderInitCallback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
