/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_autotalent_Autotalent */

#ifndef _Included_net_sourceforge_autotalent_Autotalent
#define _Included_net_sourceforge_autotalent_Autotalent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    getLiveCorrectionEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_sourceforge_autotalent_Autotalent_getLiveCorrectionEnabled
  (JNIEnv *, jclass);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    instantiateAutotalent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_instantiateAutotalent
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setConcertA
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setConcertA
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setKey
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setKey
  (JNIEnv *, jclass, jchar);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setFixedPitch
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setFixedPitch
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setFixedPull
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setFixedPull
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setCorrectionStrength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setCorrectionStrength
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setCorrectionSmoothness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setCorrectionSmoothness
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setPitchShift
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setPitchShift
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setScaleRotate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setScaleRotate
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setLfoDepth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setLfoDepth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setLfoRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setLfoRate
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setLfoShape
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setLfoShape
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setLfoSymmetric
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setLfoSymmetric
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setLfoQuantization
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setLfoQuantization
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setFormantCorrection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setFormantCorrection
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setFormantWarp
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setFormantWarp
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    setMix
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_setMix
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    processSamples
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_processSamples___3SI
  (JNIEnv *, jclass, jshortArray, jint);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    processSamples
 * Signature: ([S[SI)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_processSamples___3S_3SI
  (JNIEnv *, jclass, jshortArray, jshortArray, jint);

/*
 * Class:     net_sourceforge_autotalent_Autotalent
 * Method:    destroyAutotalent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_autotalent_Autotalent_destroyAutotalent
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
